# Generated by Django 3.2.9 on 2021-11-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookedslots',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.fixtimings'),
        ),
    ]
