# Generated by Django 3.2.4 on 2021-11-23 08:45

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybookedslots',
            name='date',
            field=models.DateField(default=None, validators=[student.models.myBookedSlots.validate_date]),
        ),
        migrations.AddField(
            model_name='mybookedslots',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
