# Generated by Django 3.2.4 on 2021-11-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20211123_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybookedslots',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mybookedslots',
            name='time',
        ),
    ]
