# Generated by Django 3.2.4 on 2021-11-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20211123_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mybookedslots',
            name='time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonggg', related_query_name='belonggg', to='student.timings'),
        ),
    ]
