# Generated by Django 3.2.4 on 2021-11-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20211123_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mybookedslots',
            name='time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongss', related_query_name='belongss', to='student.fixtimings'),
        ),
        migrations.DeleteModel(
            name='Timings',
        ),
    ]
