# Generated by Django 3.2.4 on 2021-11-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20211123_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixtimings',
            old_name='date',
            new_name='time',
        ),
    ]
