# Generated by Django 3.2.4 on 2021-11-23 09:51

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_rename_date_fixtimings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookedslots',
            name='date',
            field=models.DateField(default=None, validators=[student.models.myBookedSlots.validate_date]),
        ),
        migrations.AlterField(
            model_name='mybookedslots',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='belongss', related_query_name='belongss', to='student.fixtimings'),
        ),
    ]
